### ISSUE TITLE
User registration API validation error

### ISSUE THREAD

**Issue by masonc15** [Bregann/RetroTrack#12]
Hello,

I am having an error when registering for RetroTrack.  I have ensured that my RetroAchievements username and API key (as found at https://retroachievements.org/controlpanel.php) are correct.  I have even regenerated the API key to no avail.

When I press the "Register" button, I get an error saying:
```
Error registering user
Error validating API key. Please double check your username and RetroAchievements API key and try again
```

Any help would be appreciated.  Thank you!

**Comment by Bregann** [comment]
Hey, the retroachievements API is currently down so I'm not able to process registrations currently. Hopefully the api will be back soon 🙂 I'll update this once it's back up

**Comment by masonc15** [comment]
Ah, that would explain it -- sorry about that.  Thanks, much appreciated!

**Comment by masonc15** [comment]
@Bregann Looks like the RetroAchievements API is back up!  Let me know whenever you get a chance to update the RetroTrack side, thanks!

**Comment by Bregann** [comment]
@masonc15 Should be working now I believe 😄

**Comment by KreatureAnimal** [comment]
Im currently with the same issue i can't register im hyped for this site to be back soon i hope

**Comment by Bregann** [comment]
I've just added in some extra logging and a couple other bits and tested it locally and registering is working fine. Could you try again?

**Comment by KreatureAnimal** [comment]
Still having problems registering

**Comment by Bregann** [comment]
Hmm ok, I think the API is having some issues - they've said they're down till some server maintenance is done which should be over in about 11 hours or so from now
